-- ─── Migration 002: Zero-LLM Destination Recommendations ─────────────────────

-- Destination catalog — curated database of Indian destinations
CREATE TABLE destination_catalog (
  id               uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  name             text NOT NULL,
  state            text NOT NULL,
  pitch            text NOT NULL,
  budget_tier      text NOT NULL CHECK (budget_tier IN ('budget','midrange','premium','luxury')),
  cost_min         integer NOT NULL,
  cost_max         integer NOT NULL,
  season_ratings   integer[] NOT NULL,       -- [Jan..Dec] 1-5
  season_blocked   integer[] DEFAULT '{}',   -- 0-indexed months where travel is impossible
  season_notes     jsonb DEFAULT '{}',       -- {"6": "Monsoon brings waterfalls but leeches"}
  vibes            text[] NOT NULL,
  interest_tags    text[] DEFAULT '{}',
  pros             text[] NOT NULL,
  cons             text[] NOT NULL,
  travel_options   jsonb NOT NULL DEFAULT '[]',
  photo_url        text,
  google_place_id  text,
  lat              double precision,
  lng              double precision,
  why_templates    jsonb DEFAULT '{}',
  created_at       timestamptz DEFAULT now()
);

CREATE INDEX catalog_vibes ON destination_catalog USING gin(vibes);
CREATE INDEX catalog_budget ON destination_catalog(budget_tier);

-- Schema additions to existing tables
ALTER TABLE vibe_votes ADD COLUMN IF NOT EXISTS interest_tags text[] DEFAULT '{}';
ALTER TABLE trips ADD COLUMN IF NOT EXISTS departing_city text;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS interest_tags text[] DEFAULT '{}';
ALTER TABLE destinations ADD COLUMN IF NOT EXISTS offbeat_experiences jsonb DEFAULT '[]';
ALTER TABLE destinations ADD COLUMN IF NOT EXISTS seasonality_note text;

-- RLS for destination_catalog
ALTER TABLE destination_catalog ENABLE ROW LEVEL SECURITY;
CREATE POLICY "catalog_read" ON destination_catalog FOR SELECT USING (true);

-- ─── Seed: destination_catalog ───────────────────────────────────────────────

INSERT INTO destination_catalog (name, state, pitch, budget_tier, cost_min, cost_max, season_ratings, season_blocked, season_notes, vibes, interest_tags, pros, cons, travel_options, lat, lng, why_templates) VALUES

-- ══ BEACHES & COASTAL ══

('Goa', 'Goa',
 'Golden beaches meet Portuguese charm — India''s ultimate beach + party destination',
 'midrange', 12000, 35000,
 ARRAY[5,5,4,3,2,1,1,1,2,3,4,5],
 ARRAY[]::integer[],
 '{"5":"Pre-monsoon: last chance for beach weather","6":"Monsoon starts — many shacks close","7":"Heavy rain, rough seas, very few tourists","8":"Still monsoon but green Goa is beautiful"}'::jsonb,
 ARRAY['beach','nightlife','food','chill'],
 ARRAY['water sports','secluded beaches','clubs','live music','street food','coastal drives'],
 ARRAY['Incredible nightlife scene','Diverse beaches from party to secluded','Portuguese heritage architecture','Amazing seafood and Goan cuisine'],
 ARRAY['Overcrowded in peak season (Dec-Jan)','Tourist-trap pricing at popular beaches','Traffic congestion in North Goa'],
 '[{"from":"Delhi","mode":"flight","duration_hours":2.5,"cost_inr":4000},{"from":"Mumbai","mode":"flight","duration_hours":1,"cost_inr":2500},{"from":"Mumbai","mode":"train","duration_hours":10,"cost_inr":800},{"from":"Bangalore","mode":"flight","duration_hours":1.5,"cost_inr":3000},{"from":"Bangalore","mode":"bus","duration_hours":10,"cost_inr":900},{"from":"Pune","mode":"drive","duration_hours":8,"cost_inr":1500},{"from":"Hyderabad","mode":"flight","duration_hours":1.5,"cost_inr":3500}]'::jsonb,
 15.2993, 74.1240,
 '{"beach,nightlife":"Perfect beach-party combo — North Goa for nightlife, South Goa for chill","beach,food":"Seafood shacks on the beach + Portuguese bakeries + Goan thali crawls","beach,chill":"South Goa''s secluded beaches are made for doing absolutely nothing","nightlife,food":"Party till sunrise then recover with a Goan fish curry breakfast"}'::jsonb),

('Pondicherry', 'Puducherry',
 'French colonial charm meets Tamil soul — cafes, quiet beaches, and Auroville spirituality',
 'midrange', 10000, 28000,
 ARRAY[5,5,4,3,2,2,1,1,2,3,4,5],
 ARRAY[]::integer[],
 '{"6":"Monsoon begins — quieter but humid","10":"Post-monsoon: pleasant weather returns"}'::jsonb,
 ARRAY['beach','culture','food','chill'],
 ARRAY['secluded beaches','heritage walks','cafe hopping','cooking class','local cuisine'],
 ARRAY['Unique French-Tamil cultural blend','Amazing cafe culture and food scene','Auroville spiritual experience','Affordable compared to Goa'],
 ARRAY['Beaches are average compared to Goa','Limited nightlife','Small town — can cover in 2-3 days'],
 '[{"from":"Chennai","mode":"drive","duration_hours":3,"cost_inr":600},{"from":"Bangalore","mode":"bus","duration_hours":7,"cost_inr":700},{"from":"Delhi","mode":"flight","duration_hours":2.5,"cost_inr":5000},{"from":"Mumbai","mode":"flight","duration_hours":2,"cost_inr":4500}]'::jsonb,
 11.9416, 79.8083,
 '{"beach,culture":"French Quarter mornings + beach evenings — the perfect slow-travel combo","culture,food":"Heritage walks through White Town then Tamil-French fusion cooking classes","beach,chill":"Quiet beaches, no hawkers, just you and the Bay of Bengal"}'::jsonb),

('Gokarna', 'Karnataka',
 'Goa''s chill younger sibling — temple town with pristine beaches and zero pretension',
 'budget', 5000, 15000,
 ARRAY[5,5,4,3,2,1,1,1,2,3,4,5],
 ARRAY[]::integer[],
 '{"6":"Monsoon begins — beach shacks close","9":"Post-monsoon revival starts"}'::jsonb,
 ARRAY['beach','chill','nature','adventure'],
 ARRAY['secluded beaches','trekking','sunset spots','camping'],
 ARRAY['Untouched beaches unlike Goa','Very budget-friendly','Great beach trek route','Spiritual temple town vibe'],
 ARRAY['Limited dining options','Basic accommodation mostly','No nightlife to speak of','Getting there takes effort'],
 '[{"from":"Bangalore","mode":"bus","duration_hours":8,"cost_inr":700},{"from":"Goa","mode":"bus","duration_hours":3,"cost_inr":400},{"from":"Mumbai","mode":"train","duration_hours":12,"cost_inr":700}]'::jsonb,
 14.5479, 74.3188,
 '{"beach,chill":"Five pristine beaches connected by cliff trails — Goa without the crowds","beach,adventure":"Beach-to-beach cliff trek + camping on Om Beach under the stars"}'::jsonb),

('Andaman Islands', 'Andaman & Nicobar',
 'Turquoise waters and untouched coral reefs — India''s best-kept tropical secret',
 'premium', 30000, 60000,
 ARRAY[4,4,5,4,3,2,1,1,2,3,4,4],
 ARRAY[]::integer[],
 '{"2":"Best visibility for scuba diving","6":"Monsoon — ferries cancelled, many islands inaccessible","9":"Monsoon easing, off-season deals"}'::jsonb,
 ARRAY['beach','adventure','nature'],
 ARRAY['water sports','secluded beaches','wildlife'],
 ARRAY['Crystal clear water and coral reefs','Incredible scuba diving and snorkeling','Pristine untouched beaches','Unique history (Cellular Jail)'],
 ARRAY['Expensive flights from mainland','Limited connectivity between islands','Rainy season is long','Advance booking essential'],
 '[{"from":"Chennai","mode":"flight","duration_hours":2,"cost_inr":6000},{"from":"Kolkata","mode":"flight","duration_hours":2,"cost_inr":5500},{"from":"Delhi","mode":"flight","duration_hours":4,"cost_inr":8000},{"from":"Bangalore","mode":"flight","duration_hours":3,"cost_inr":7000}]'::jsonb,
 11.7401, 92.6586,
 '{"beach,adventure":"Scuba dive at Havelock, sea-walk at North Bay, kayak through mangroves","beach,nature":"Radhanagar Beach (Asia''s best) + bioluminescent plankton at night"}'::jsonb),

('Varkala', 'Kerala',
 'Dramatic red cliffs over Arabian Sea — Kerala''s backpacker beach with Ayurvedic soul',
 'budget', 6000, 18000,
 ARRAY[5,5,4,3,2,1,1,1,2,3,4,5],
 ARRAY[]::integer[],
 '{"5":"Pre-monsoon — sea gets rough","10":"Post-monsoon — beach restaurants reopen"}'::jsonb,
 ARRAY['beach','chill','culture'],
 ARRAY['secluded beaches','spa/wellness','sunset spots','heritage walks'],
 ARRAY['Stunning cliff-top setting','Ayurvedic massage and wellness','Budget-friendly beach destination','Ancient Janardhana temple'],
 ARRAY['Cliff erosion limits beach space','Limited nightlife','Monsoon shuts everything down','Steep cliff stairs not great for elderly'],
 '[{"from":"Kochi","mode":"train","duration_hours":3,"cost_inr":300},{"from":"Bangalore","mode":"train","duration_hours":12,"cost_inr":600},{"from":"Chennai","mode":"flight","duration_hours":1.5,"cost_inr":4000}]'::jsonb,
 8.7379, 76.7163,
 '{"beach,chill":"Cliff-top cafes, Ayurvedic massages, and zero rush — the ultimate unwind","beach,culture":"Ancient temple + papanasam holy beach + cliff heritage walk"}'::jsonb),

('Alleppey', 'Kerala',
 'Venice of the East — houseboat through palm-fringed backwaters with Kerala cuisine',
 'midrange', 12000, 30000,
 ARRAY[4,4,4,3,2,2,2,2,3,4,5,5],
 ARRAY[]::integer[],
 '{"7":"Monsoon — backwaters overflow, very green but rainy","8":"Nehru Trophy boat race month","11":"Best weather, post-monsoon green"}'::jsonb,
 ARRAY['nature','chill','food'],
 ARRAY['coastal drives','local cuisine','sunset spots'],
 ARRAY['Unique houseboat overnight experience','Stunning backwater scenery','Incredible Kerala cuisine','Peaceful and romantic'],
 ARRAY['Houseboats can be overpriced','Mosquitoes in the evening','Limited activities beyond backwaters','Traffic jam of houseboats in peak season'],
 '[{"from":"Kochi","mode":"drive","duration_hours":1.5,"cost_inr":400},{"from":"Bangalore","mode":"train","duration_hours":11,"cost_inr":600},{"from":"Mumbai","mode":"flight","duration_hours":2,"cost_inr":4500}]'::jsonb,
 9.4981, 76.3388,
 '{"nature,food":"Houseboat lunch of karimeen fry while drifting through palm canals","nature,chill":"Float through backwaters with zero agenda — the definition of slow travel"}'::jsonb),

-- ══ MOUNTAINS & HILL STATIONS ══

('Manali', 'Himachal Pradesh',
 'Himalayan adventure hub — snow peaks, river rafting, and Old Manali cafe culture',
 'midrange', 12000, 35000,
 ARRAY[3,3,3,4,5,4,2,2,3,5,4,3],
 ARRAY[]::integer[],
 '{"0":"Snow season — Rohtang closed, town is cold but beautiful","4":"Spring bloom, perfect trekking weather","6":"Monsoon — landslides on NH-3","9":"Post-monsoon clarity — best mountain views"}'::jsonb,
 ARRAY['mountains','adventure','nature','chill'],
 ARRAY['trekking','snow','valley views','cafe hopping','rafting','camping'],
 ARRAY['Year-round destination','Adventure activities galore','Old Manali hippy-cafe culture','Gateway to Leh-Ladakh and Spiti'],
 ARRAY['Extremely crowded in summer','NH-3 traffic jams legendary','Over-commercialized Mall Road','Monsoon landslides disrupt travel'],
 '[{"from":"Delhi","mode":"bus","duration_hours":14,"cost_inr":900},{"from":"Delhi","mode":"flight","duration_hours":1.5,"cost_inr":4500},{"from":"Chandigarh","mode":"bus","duration_hours":8,"cost_inr":600}]'::jsonb,
 32.2396, 77.1887,
 '{"mountains,adventure":"Hampta Pass trek + Solang Valley paragliding + Beas river rafting","mountains,chill":"Old Manali cafes + hot springs at Vashisht + apple orchard walks","adventure,nature":"Trek to Jogini Falls then camp under Himalayan stars"}'::jsonb),

('Ladakh', 'Ladakh',
 'Moonscapes and monastery magic — the roof of India at 11,000ft',
 'premium', 25000, 55000,
 ARRAY[1,1,1,2,3,5,5,5,5,4,2,1],
 ARRAY[0,1,2,3],
 '{"4":"Roads opening, still cold, few tourists","5":"Season begins — Pangong still frozen","6":"Peak season starts, warm days","8":"Monsoon clouds but rarely rains in Ladakh","9":"Best month — clear skies, warm, fewer tourists","10":"Season ending, cold nights return"}'::jsonb,
 ARRAY['mountains','adventure','culture','nature'],
 ARRAY['trekking','valley views','religious sites','camping','wildlife'],
 ARRAY['Otherworldly landscapes','Ancient Buddhist monasteries','Pangong Lake is breathtaking','Incredible stargazing at altitude'],
 ARRAY['Altitude sickness is real — acclimatize 2 days','Roads closed Nov-Apr','Expensive due to remoteness','Limited medical facilities'],
 '[{"from":"Delhi","mode":"flight","duration_hours":1.5,"cost_inr":6000},{"from":"Delhi","mode":"drive","duration_hours":36,"cost_inr":3000},{"from":"Manali","mode":"drive","duration_hours":18,"cost_inr":2000}]'::jsonb,
 34.1526, 77.5771,
 '{"mountains,adventure":"Khardung La pass + Pangong camping + Nubra Valley camel ride","mountains,culture":"Hemis and Thiksey monasteries + prayer flag passes + local cuisine","adventure,nature":"Markha Valley trek through nomad camps and 5000m passes"}'::jsonb),

('Shimla', 'Himachal Pradesh',
 'Colonial hill station with toy train charm — the OG Indian mountain getaway',
 'midrange', 10000, 25000,
 ARRAY[3,3,3,4,5,4,2,2,3,4,4,3],
 ARRAY[]::integer[],
 '{"0":"Snow possible — scenic but cold","4":"Cherry blossom season","6":"Monsoon — landslides possible on NH-5","11":"Winter starts, fewer tourists"}'::jsonb,
 ARRAY['mountains','culture','chill'],
 ARRAY['heritage walks','hill station','cafe hopping'],
 ARRAY['UNESCO toy train experience','Well-connected from Delhi','Rich colonial architecture','Pleasant weather most of the year'],
 ARRAY['Extremely crowded on weekends','Over-commercialized Mall Road','Traffic nightmare in peak season','Losing old-world charm to construction'],
 '[{"from":"Delhi","mode":"bus","duration_hours":8,"cost_inr":600},{"from":"Delhi","mode":"train","duration_hours":10,"cost_inr":400},{"from":"Chandigarh","mode":"drive","duration_hours":3,"cost_inr":500}]'::jsonb,
 31.1048, 77.1734,
 '{"mountains,culture":"Toy train + Viceregal Lodge + Jakhu temple + Christ Church walk","mountains,chill":"Mall Road strolls + Scandal Point sunsets + colonial cafe hopping"}'::jsonb),

('Coorg', 'Karnataka',
 'Scotland of India — misty coffee estates, waterfalls, and Kodava warrior culture',
 'midrange', 10000, 28000,
 ARRAY[4,4,3,3,3,3,4,4,3,4,5,5],
 ARRAY[]::integer[],
 '{"5":"Pre-monsoon — mist and occasional showers","6":"Monsoon brings waterfalls to peak glory","9":"Post-monsoon green — everything is lush","10":"Perfect weather begins"}'::jsonb,
 ARRAY['nature','chill','food','adventure'],
 ARRAY['waterfalls','forests','cooking class','trekking','wildlife','local cuisine','cafe hopping'],
 ARRAY['Stunning coffee plantation stays','Amazing Kodava cuisine','Misty monsoon waterfalls','Off-the-beaten-path feel'],
 ARRAY['Limited public transport','Leeches in monsoon season','Gets foggy — visibility can be zero','Weekend crowds from Bangalore'],
 '[{"from":"Bangalore","mode":"drive","duration_hours":5,"cost_inr":800},{"from":"Mysore","mode":"drive","duration_hours":3,"cost_inr":500},{"from":"Mangalore","mode":"drive","duration_hours":4,"cost_inr":600}]'::jsonb,
 12.3375, 75.8069,
 '{"nature,food":"Coffee estate mornings + Kodava cooking class + waterfall trek afternoons","nature,chill":"Wake up in a misty plantation, do nothing, repeat","adventure,nature":"Mandalpatti peak trek + Iruppu Falls + Dubare elephant camp"}'::jsonb),

('Darjeeling', 'West Bengal',
 'Queen of the Hills — tea gardens, toy train, and Kanchenjunga sunrise at Tiger Hill',
 'midrange', 10000, 25000,
 ARRAY[3,3,4,5,5,3,1,1,2,5,4,3],
 ARRAY[]::integer[],
 '{"3":"Spring — rhododendrons bloom, clear skies","4":"Best month — clear Kanchenjunga views","6":"Monsoon — heavy rain, landslides","9":"Post-monsoon — tea gardens at greenest"}'::jsonb,
 ARRAY['mountains','culture','nature','chill'],
 ARRAY['heritage walks','hill station','cafe hopping','local cuisine','valley views'],
 ARRAY['Iconic Kanchenjunga sunrise','UNESCO toy train heritage','World-famous tea gardens','Rich Tibetan-Nepali culture'],
 ARRAY['Very crowded in peak season','Monsoon landslides cut off roads','Altitude can cause mild sickness','Limited nightlife'],
 '[{"from":"Kolkata","mode":"flight","duration_hours":1,"cost_inr":4000},{"from":"Kolkata","mode":"train","duration_hours":10,"cost_inr":500},{"from":"Delhi","mode":"flight","duration_hours":2,"cost_inr":5500}]'::jsonb,
 27.0410, 88.2663,
 '{"mountains,culture":"Tiger Hill sunrise + monastery walk + tea garden tour + toy train","nature,chill":"Tea estate mornings + Himalayan views + cafe hopping in Darjeeling town"}'::jsonb),

('Mussoorie', 'Uttarakhand',
 'Queen of Hill Stations — Doon Valley views, Landour bakeries, and monsoon magic',
 'midrange', 8000, 22000,
 ARRAY[3,3,4,5,5,4,3,3,3,4,4,3],
 ARRAY[]::integer[],
 '{"4":"Perfect spring weather","6":"Monsoon clouds — misty, romantic, green","11":"Winter starts — cold but clear"}'::jsonb,
 ARRAY['mountains','chill','nature','culture'],
 ARRAY['heritage walks','cafe hopping','hill station','valley views'],
 ARRAY['Easy access from Delhi (6hrs)','Charming Landour cantonment area','Great monsoon destination','Camel''s Back Road walks'],
 ARRAY['Mall Road is overcrowded','Weekend traffic from Delhi','Commercialized in parts','Limited adventure activities'],
 '[{"from":"Delhi","mode":"drive","duration_hours":6,"cost_inr":800},{"from":"Delhi","mode":"train","duration_hours":5.5,"cost_inr":400}]'::jsonb,
 30.4598, 78.0644,
 '{"mountains,chill":"Landour bakery breakfast + Camel''s Back sunset walk + cloud watching","culture,chill":"Ruskin Bond''s Landour + colonial churches + Char Dukan cafe stop"}'::jsonb),

('Munnar', 'Kerala',
 'Endless tea carpets on misty hills — Kerala''s emerald hill station',
 'midrange', 10000, 25000,
 ARRAY[4,4,4,3,3,2,2,2,3,4,5,5],
 ARRAY[]::integer[],
 '{"3":"Neelakurinji bloom (once in 12 years)","6":"Monsoon — misty, waterfalls peak","10":"Best weather starts, tea plucking season"}'::jsonb,
 ARRAY['nature','chill','mountains'],
 ARRAY['trekking','valley views','wildlife','waterfalls'],
 ARRAY['Stunning tea garden landscapes','Pleasant weather year-round','Eravikulam National Park','Budget-friendly Kerala hill station'],
 ARRAY['Hairpin roads — motion sickness common','Touristy at popular viewpoints','Limited dining variety','Cold and foggy in monsoon'],
 '[{"from":"Kochi","mode":"drive","duration_hours":4,"cost_inr":600},{"from":"Bangalore","mode":"drive","duration_hours":9,"cost_inr":1200},{"from":"Chennai","mode":"drive","duration_hours":10,"cost_inr":1300}]'::jsonb,
 10.0889, 77.0595,
 '{"nature,chill":"Tea garden walks at dawn + Mattupetty Dam boating + spice plantation tour","mountains,nature":"Anamudi peak trek + Eravikulam wildlife + Top Station panoramas"}'::jsonb),

('Ooty', 'Tamil Nadu',
 'Nilgiris'' crown jewel — toy train, botanical gardens, and eucalyptus-scented trails',
 'midrange', 8000, 22000,
 ARRAY[4,4,4,4,5,3,2,2,3,5,5,4],
 ARRAY[]::integer[],
 '{"4":"Summer — perfect weather, peak crowds","6":"Monsoon starts — misty and cool","10":"Post-monsoon — clear and pleasant"}'::jsonb,
 ARRAY['nature','chill','mountains'],
 ARRAY['hill station','valley views','cafe hopping'],
 ARRAY['UNESCO Nilgiri Mountain Railway','Beautiful botanical gardens','Pleasant weather','Good for families and groups'],
 ARRAY['Extremely crowded in summer','Commercialized lake area','Traffic on Ghat road','Limited adventure activities'],
 '[{"from":"Bangalore","mode":"drive","duration_hours":6,"cost_inr":700},{"from":"Coimbatore","mode":"train","duration_hours":5,"cost_inr":200},{"from":"Mysore","mode":"drive","duration_hours":4,"cost_inr":500}]'::jsonb,
 11.4102, 76.6950,
 '{"nature,chill":"Botanical garden strolls + Nilgiri toy train + Doddabetta Peak sunset"}'::jsonb),

-- ══ CULTURE & HERITAGE ══

('Jaipur', 'Rajasthan',
 'Pink City royalty — forts, bazaars, and Rajasthani thali that hits different',
 'midrange', 10000, 30000,
 ARRAY[5,5,4,3,2,1,1,1,2,4,5,5],
 ARRAY[]::integer[],
 '{"3":"Holi celebrations are spectacular here","4":"Getting hot — avoid afternoon sightseeing","5":"Extreme heat begins","10":"Festival season — Diwali lights up the city","11":"Perfect weather returns"}'::jsonb,
 ARRAY['culture','food','adventure'],
 ARRAY['heritage walks','religious sites','local festivals','crafts','street food','local cuisine'],
 ARRAY['Incredible Rajput architecture','UNESCO World Heritage sites','Amazing street food scene','Great shopping — block prints, jewelry'],
 ARRAY['Scorching hot Apr-Jun','Tourist-trap pricing common','Aggressive touts at monuments','Traffic chaos in old city'],
 '[{"from":"Delhi","mode":"train","duration_hours":4.5,"cost_inr":500},{"from":"Delhi","mode":"drive","duration_hours":5,"cost_inr":700},{"from":"Mumbai","mode":"flight","duration_hours":2,"cost_inr":4000},{"from":"Bangalore","mode":"flight","duration_hours":2.5,"cost_inr":5000}]'::jsonb,
 26.9124, 75.7873,
 '{"culture,food":"Amber Fort morning + Johri Bazaar thali crawl + evening light show","culture,adventure":"Fort trekking + hot air balloon over Pink City + Nahargarh sunset"}'::jsonb),

('Udaipur', 'Rajasthan',
 'City of Lakes — white marble palaces floating on water, the most romantic city in India',
 'midrange', 12000, 35000,
 ARRAY[5,5,4,3,2,1,1,1,2,4,5,5],
 ARRAY[]::integer[],
 '{"3":"Pleasant but warming up","5":"Extreme heat — not recommended","7":"Monsoon fills the lakes — stunning","10":"Festival season begins"}'::jsonb,
 ARRAY['culture','chill','food'],
 ARRAY['heritage walks','crafts','sunset spots','local cuisine','cafe hopping'],
 ARRAY['Lake Pichola is breathtaking','City Palace is magnificent','Romantic sunset boat rides','Amazing rooftop restaurants'],
 ARRAY['Hot and dry Apr-Jun','Tourist prices everywhere','Crowded in peak season','Lakes can dry up in summer'],
 '[{"from":"Delhi","mode":"flight","duration_hours":1.5,"cost_inr":4000},{"from":"Jaipur","mode":"drive","duration_hours":5,"cost_inr":700},{"from":"Mumbai","mode":"flight","duration_hours":1.5,"cost_inr":3500},{"from":"Ahmedabad","mode":"drive","duration_hours":4,"cost_inr":600}]'::jsonb,
 24.5854, 73.7125,
 '{"culture,chill":"Palace sunrise + lake boat ride + rooftop dinner with Aravalli views","culture,food":"Old city heritage walk + dal baati churma + miniature painting workshop"}'::jsonb),

('Varanasi', 'Uttar Pradesh',
 'The oldest living city — Ganga ghats, ancient temples, and spiritual fire ceremonies',
 'budget', 5000, 15000,
 ARRAY[4,4,3,2,1,1,1,1,2,4,5,5],
 ARRAY[]::integer[],
 '{"3":"Holi — the most intense celebration anywhere","4":"Getting very hot","10":"Dev Deepawali — million diyas on the ghats","11":"Best weather for ghat walks"}'::jsonb,
 ARRAY['culture','food'],
 ARRAY['heritage walks','religious sites','street food','local cuisine','local festivals'],
 ARRAY['Ganga Aarti is unforgettable','Oldest continuously inhabited city','Incredible street food (kachori, lassi)','Deep spiritual experience'],
 ARRAY['Extremely hot in summer','Can be overwhelming for first-timers','Aggressive boat touts','Narrow gali streets are confusing'],
 '[{"from":"Delhi","mode":"train","duration_hours":8,"cost_inr":500},{"from":"Delhi","mode":"flight","duration_hours":1.5,"cost_inr":3500},{"from":"Kolkata","mode":"flight","duration_hours":1.5,"cost_inr":3000}]'::jsonb,
 25.3176, 83.0103,
 '{"culture,food":"Morning Ganga boat ride + ghat walk + Blue Lassi + Kashi Vishwanath + evening Aarti","culture":"Subah-e-Banaras dawn walk + silk weaving village + Sarnath Buddhist circuit"}'::jsonb),

('Hampi', 'Karnataka',
 'Boulder-strewn ruins of Vijayanagara — where ancient temples meet surreal landscapes',
 'budget', 4000, 12000,
 ARRAY[5,4,3,2,1,1,1,1,2,4,5,5],
 ARRAY[]::integer[],
 '{"3":"Getting hot — carry water","4":"Extreme heat begins","10":"Post-monsoon — green and pleasant","11":"Best month — cool, clear, perfect"}'::jsonb,
 ARRAY['culture','adventure','nature'],
 ARRAY['heritage walks','trekking','religious sites','sunset spots'],
 ARRAY['UNESCO World Heritage site','Surreal boulder landscape','Incredibly budget-friendly','Unique hippie-meets-history vibe'],
 ARRAY['Scorching hot Mar-Jun','Very basic accommodation','Limited food options','Remote location'],
 '[{"from":"Bangalore","mode":"bus","duration_hours":7,"cost_inr":600},{"from":"Goa","mode":"bus","duration_hours":7,"cost_inr":500},{"from":"Hyderabad","mode":"train","duration_hours":8,"cost_inr":400}]'::jsonb,
 15.3350, 76.4600,
 '{"culture,adventure":"Virupaksha temple + Matanga Hill sunrise trek + coracle ride on Tungabhadra","culture,nature":"Ruins exploration by bicycle + Hippie Island sunset + boulder scrambling"}'::jsonb),

('Khajuraho', 'Madhya Pradesh',
 'Erotic temple art that shocked the British — UNESCO masterpieces of medieval sculpture',
 'budget', 5000, 15000,
 ARRAY[5,4,3,2,1,1,1,1,2,4,5,5],
 ARRAY[]::integer[],
 '{"2":"Dance festival (Feb) — classical performances at temple backdrop","4":"Getting very hot","10":"Best weather returns"}'::jsonb,
 ARRAY['culture'],
 ARRAY['heritage walks','religious sites','local festivals'],
 ARRAY['UNESCO-quality temple sculptures','Unique erotic art tradition','Uncrowded compared to Rajasthan','Light and sound show is excellent'],
 ARRAY['Remote — limited flight connectivity','Very hot in summer','Can be covered in 1-2 days','Limited food and nightlife'],
 '[{"from":"Delhi","mode":"flight","duration_hours":1.5,"cost_inr":4000},{"from":"Varanasi","mode":"drive","duration_hours":8,"cost_inr":1200}]'::jsonb,
 24.8318, 79.9199,
 '{"culture":"Western group temples + Eastern temples bicycle tour + Sound & Light Show"}'::jsonb),

('Mysore', 'Karnataka',
 'City of Palaces — Dasara grandeur, sandalwood, and South Indian royal heritage',
 'budget', 6000, 18000,
 ARRAY[4,4,4,4,4,3,3,3,3,5,5,5],
 ARRAY[]::integer[],
 '{"9":"Dasara festival (Sep/Oct) — 10-day royal celebration, must-visit","10":"Dasara grand finale — illuminated palace"}'::jsonb,
 ARRAY['culture','food','chill'],
 ARRAY['heritage walks','local cuisine','crafts','religious sites'],
 ARRAY['Magnificent Mysore Palace','Chamundi Hill temple views','Amazing South Indian food','Clean, well-planned city'],
 ARRAY['Can be covered in 2 days','Limited nightlife','Very hot in April-May','Tourist shops overpriced'],
 '[{"from":"Bangalore","mode":"train","duration_hours":2.5,"cost_inr":200},{"from":"Bangalore","mode":"drive","duration_hours":3,"cost_inr":400}]'::jsonb,
 12.2958, 76.6394,
 '{"culture,food":"Palace tour + Devaraja Market walk + Mysore Pak at Guru Sweets + Chamundi Hill","culture,chill":"Palace morning + Brindavan Gardens evening + lazy Mysore filter coffee"}'::jsonb),

-- ══ ADVENTURE & NATURE ══

('Rishikesh', 'Uttarakhand',
 'Yoga capital meets adventure playground — where spiritual seekers and rafters coexist',
 'budget', 5000, 18000,
 ARRAY[4,4,4,4,4,3,2,2,3,5,5,4],
 ARRAY[]::integer[],
 '{"3":"Rafting season ends mid-March due to dam release","4":"Hot but pleasant mornings for yoga","6":"Monsoon — rafting suspended, Ganga floods","9":"Rafting season resumes"}'::jsonb,
 ARRAY['adventure','chill','nature','culture'],
 ARRAY['rafting','trekking','camping','spa/wellness','religious sites','cafe hopping'],
 ARRAY['World-class white water rafting','Yoga and meditation retreats','Bungee jumping and cliff jumping','Beatles Ashram and Ram Jhula'],
 ARRAY['Overcrowded on weekends','Monsoon makes river dangerous','Tourist-trap yoga centers','Traffic on main road'],
 '[{"from":"Delhi","mode":"drive","duration_hours":6,"cost_inr":700},{"from":"Delhi","mode":"bus","duration_hours":7,"cost_inr":500}]'::jsonb,
 30.0869, 78.2676,
 '{"adventure,chill":"Morning yoga + afternoon rafting + evening Ganga Aarti — perfect balance","adventure,nature":"Grade 4 rapids + cliff jumping + camping on the Ganga bank"}'::jsonb),

('Spiti Valley', 'Himachal Pradesh',
 'Cold desert monastery magic — the most remote inhabited valley in India',
 'midrange', 15000, 35000,
 ARRAY[1,1,1,1,3,5,4,4,5,4,2,1],
 ARRAY[0,1,2,3],
 '{"4":"Roads start opening — still risky","5":"Season begins, Kunzum Pass opens","6":"Best month — warm days, clear skies","8":"Monsoon doesn''t reach Spiti — advantage over Ladakh","9":"Last good month before roads close"}'::jsonb,
 ARRAY['mountains','adventure','culture','nature'],
 ARRAY['trekking','valley views','religious sites','camping','wildlife'],
 ARRAY['Truly remote and untouched','Ancient Buddhist monasteries','Milky Way visible to naked eye','No crowds ever'],
 ARRAY['Roads closed Nov-Apr','Altitude sickness at 4000m+','Very basic facilities','No ATMs — carry cash'],
 '[{"from":"Delhi","mode":"drive","duration_hours":24,"cost_inr":3000},{"from":"Manali","mode":"drive","duration_hours":10,"cost_inr":1500},{"from":"Shimla","mode":"drive","duration_hours":12,"cost_inr":2000}]'::jsonb,
 32.2464, 78.0349,
 '{"mountains,adventure":"Key Monastery + Chandratal Lake trek + Kunzum Pass crossing","mountains,culture":"1000-year-old monasteries + Tabo caves + Dhankar lake trek","adventure,nature":"Pin Valley snow leopard territory + fossil hunting + stargazing at 14,000ft"}'::jsonb),

('Jim Corbett', 'Uttarakhand',
 'India''s oldest tiger reserve — where the jungle book comes alive',
 'midrange', 12000, 30000,
 ARRAY[4,4,4,4,4,3,1,1,2,4,5,5],
 ARRAY[6,7],
 '{"2":"Best tiger sighting odds — dry season, animals at waterholes","6":"Park closes for monsoon","10":"Park reopens — lush green jungle","11":"Excellent wildlife season begins"}'::jsonb,
 ARRAY['nature','adventure'],
 ARRAY['wildlife','forests','camping'],
 ARRAY['Best tiger sighting probability in India','Beautiful sal forest landscape','Close to Delhi (5-6hrs)','Good resort infrastructure'],
 ARRAY['Expensive park entry for foreigners','Core zones book out months ahead','Monsoon closure (Jun-Sep)','Limited activities beyond safari'],
 '[{"from":"Delhi","mode":"drive","duration_hours":5,"cost_inr":700},{"from":"Delhi","mode":"train","duration_hours":5,"cost_inr":400}]'::jsonb,
 29.5300, 78.7747,
 '{"nature,adventure":"Tiger safari at dawn + elephant ride through sal forest + river fishing"}'::jsonb),

('Meghalaya', 'Meghalaya',
 'Abode of Clouds — living root bridges, cleanest village in Asia, and endless waterfalls',
 'midrange', 12000, 30000,
 ARRAY[3,3,4,4,4,3,2,2,3,5,5,4],
 ARRAY[]::integer[],
 '{"3":"Pre-monsoon — pleasant, waterfalls starting","6":"Heavy rain (wettest place on earth) — dramatic but challenging","10":"Post-monsoon — waterfalls peak, clear skies","11":"Best month — perfect weather, Wangala festival"}'::jsonb,
 ARRAY['nature','adventure','culture'],
 ARRAY['trekking','waterfalls','offbeat villages','forests','wildlife'],
 ARRAY['Living root bridges are mind-blowing','Cleanest village in Asia (Mawlynnong)','Dramatic waterfall landscapes','Unique Khasi culture'],
 ARRAY['Remote — limited connectivity','Heavy monsoon rain Jun-Aug','Basic accommodation in rural areas','Long drives on winding roads'],
 '[{"from":"Guwahati","mode":"drive","duration_hours":3,"cost_inr":500},{"from":"Kolkata","mode":"flight","duration_hours":1.5,"cost_inr":4000},{"from":"Delhi","mode":"flight","duration_hours":3,"cost_inr":5500}]'::jsonb,
 25.4670, 91.3662,
 '{"nature,adventure":"Double-decker root bridge trek + Dawki crystal river + Mawsmai caves","nature,culture":"Mawlynnong village + Nohkalikai Falls + Khasi market + cave exploration"}'::jsonb),

('Ranthambore', 'Rajasthan',
 'Where tigers roam ancient Rajput ruins — India''s most photogenic wildlife reserve',
 'midrange', 12000, 30000,
 ARRAY[4,4,3,3,2,1,1,1,2,5,5,5],
 ARRAY[5,6,7,8],
 '{"1":"Peak winter safari — tigers bask in sun","3":"Dry season — excellent sightings near water","5":"Park closes for monsoon","10":"Park reopens — green canopy, fresh energy"}'::jsonb,
 ARRAY['nature','adventure'],
 ARRAY['wildlife','forests'],
 ARRAY['Tigers pose with ancient fort ruins','High sighting probability','Close to Jaipur (3hrs)','Unique fort-inside-jungle setting'],
 ARRAY['Closed Jun-Sep for monsoon','Safari permits hard to get','Hot in pre-monsoon months','Very expensive in peak season'],
 '[{"from":"Jaipur","mode":"drive","duration_hours":3,"cost_inr":500},{"from":"Delhi","mode":"train","duration_hours":5,"cost_inr":400}]'::jsonb,
 26.0173, 76.5026,
 '{"nature,adventure":"Tiger safari + Ranthambore Fort trek + crocodile spotting at Padam Talao"}'::jsonb),

-- ══ NORTHEAST ══

('Kaziranga', 'Assam',
 'One-horned rhino kingdom — UNESCO site with the highest density of tigers in India',
 'midrange', 12000, 28000,
 ARRAY[4,4,4,4,3,1,1,1,2,4,5,5],
 ARRAY[5,6,7,8],
 '{"1":"Best wildlife viewing — dry grasslands","3":"Holi + good sightings","5":"Park closes for monsoon","10":"Park reopens"}'::jsonb,
 ARRAY['nature','adventure'],
 ARRAY['wildlife','forests'],
 ARRAY['One-horned rhino guaranteed sighting','Highest tiger density in India','UNESCO World Heritage','Elephant safari through tall grass'],
 ARRAY['Closed Jun-Sep','Very limited accommodation','Remote location','Poaching concerns'],
 '[{"from":"Guwahati","mode":"drive","duration_hours":4,"cost_inr":600},{"from":"Delhi","mode":"flight","duration_hours":3,"cost_inr":5000}]'::jsonb,
 26.5775, 93.1711,
 '{"nature,adventure":"Elephant safari + jeep safari + Brahmaputra river cruise"}'::jsonb),

('Tawang', 'Arunachal Pradesh',
 'India''s hidden Himalayan gem — 400-year-old monastery, war memorial, and alpine lakes',
 'midrange', 15000, 30000,
 ARRAY[3,3,4,5,5,3,1,1,2,5,4,3],
 ARRAY[6,7],
 '{"3":"Losar festival — Tibetan New Year celebrations","4":"Best month — clear skies, warm days","5":"Spring flowers + perfect trekking","9":"Post-monsoon — dramatic clouds"}'::jsonb,
 ARRAY['mountains','culture','nature','adventure'],
 ARRAY['religious sites','trekking','valley views','offbeat villages'],
 ARRAY['Largest monastery in India','Sela Pass at 13,700ft is stunning','Zero commercialization','Rich Monpa tribal culture'],
 ARRAY['Requires Inner Line Permit','Very remote — 2-day drive from Guwahati','Basic facilities','Altitude sickness risk','Road conditions poor in monsoon'],
 '[{"from":"Guwahati","mode":"drive","duration_hours":14,"cost_inr":2000},{"from":"Tezpur","mode":"drive","duration_hours":8,"cost_inr":1200}]'::jsonb,
 27.5860, 91.8597,
 '{"mountains,culture":"Tawang Monastery + Sela Pass + war memorial + Madhuri Lake","adventure,nature":"Bum La Pass border trek + PTSO Lake + Gorichen Base Camp"}'::jsonb),

('Shillong', 'Meghalaya',
 'Scotland of the East — rolling hills, live music, and the coolest college town in India',
 'budget', 8000, 20000,
 ARRAY[3,3,4,4,5,3,2,2,3,5,5,4],
 ARRAY[]::integer[],
 '{"4":"Cherry blossom season","6":"Heavy rain starts","10":"Perfect weather + autumn festivals"}'::jsonb,
 ARRAY['nature','chill','culture','food'],
 ARRAY['cafe hopping','live music','waterfalls','local cuisine','offbeat villages'],
 ARRAY['Amazing live music scene','Cool weather year-round','Vibrant cafe culture','Gateway to Meghalaya adventures'],
 ARRAY['Limited direct flights','Rain can be persistent','Weekend traffic from Guwahati','Limited luxury accommodation'],
 '[{"from":"Guwahati","mode":"drive","duration_hours":2,"cost_inr":300},{"from":"Kolkata","mode":"flight","duration_hours":1.5,"cost_inr":4000}]'::jsonb,
 25.5788, 91.8933,
 '{"chill,food":"Cafe hop through Police Bazaar + Don Bosco Museum + Khasi street food + live music night","nature,culture":"Ward''s Lake + Elephant Falls + Laitlum Grand Canyon + Nongkrem dance"}'::jsonb),

-- ══ DESERT & UNIQUE ══

('Jaisalmer', 'Rajasthan',
 'Golden city rising from the Thar — sandstone fort, desert camps, and starry nights',
 'midrange', 10000, 25000,
 ARRAY[5,5,4,3,1,1,1,1,2,4,5,5],
 ARRAY[]::integer[],
 '{"3":"Desert festival (Feb/Mar) — camel races, folk performances","4":"Too hot to enjoy desert","10":"Pleasant weather returns","11":"Best month — cool desert nights, clear skies"}'::jsonb,
 ARRAY['culture','adventure','nature'],
 ARRAY['camping','heritage walks','sunset spots','local festivals'],
 ARRAY['Living fort — people still live inside','Incredible desert camping under stars','Sam Sand Dunes sunset','Unique golden sandstone architecture'],
 ARRAY['Extreme heat Apr-Aug','Remote — long journey from Delhi','Limited food variety','Tourist camel rides can be exploitative'],
 '[{"from":"Delhi","mode":"train","duration_hours":12,"cost_inr":600},{"from":"Jaipur","mode":"train","duration_hours":5,"cost_inr":400},{"from":"Jodhpur","mode":"drive","duration_hours":5,"cost_inr":600}]'::jsonb,
 26.9157, 70.9083,
 '{"culture,adventure":"Golden Fort walk + desert camping + Sam Dunes sunset camel ride + stargazing","adventure,nature":"Thar desert jeep safari + Desert National Park + Kuldhara ghost village"}'::jsonb),

('Kutch', 'Gujarat',
 'White desert stretching to the horizon — Rann Utsav, tribal art, and flamingo sunrises',
 'midrange', 10000, 25000,
 ARRAY[5,4,3,2,1,1,1,1,1,3,5,5],
 ARRAY[]::integer[],
 '{"0":"Rann Utsav festival (Nov-Feb) — the main draw","6":"Monsoon — Rann is underwater","11":"Festival begins — full moon nights on white salt flat"}'::jsonb,
 ARRAY['culture','nature','adventure'],
 ARRAY['local festivals','crafts','wildlife','sunset spots','offbeat villages'],
 ARRAY['Rann Utsav is a once-in-a-lifetime experience','Unique white salt desert','Vibrant tribal handicrafts','Flamingo sanctuary at sunrise'],
 ARRAY['Only worth visiting Nov-Feb','Very hot rest of the year','Remote location','Limited luxury options'],
 '[{"from":"Ahmedabad","mode":"drive","duration_hours":5,"cost_inr":700},{"from":"Mumbai","mode":"flight","duration_hours":1.5,"cost_inr":3500}]'::jsonb,
 23.7337, 69.8597,
 '{"culture,nature":"White Rann full-moon walk + Bhuj tribal village + flamingo sanctuary sunrise","culture,adventure":"Salt desert motorcycle + Bhuj artisan workshops + Mandvi beach fort"}'::jsonb),

-- ══ SPIRITUAL & WELLNESS ══

('McLeod Ganj', 'Himachal Pradesh',
 'Little Tibet in the Himalayas — Dalai Lama''s home, momos, and mountain monasteries',
 'budget', 5000, 15000,
 ARRAY[3,3,4,5,5,4,2,2,3,5,4,3],
 ARRAY[]::integer[],
 '{"3":"Tibetan New Year (Losar)","4":"Best weather — clear Dhauladhar views","6":"Monsoon — heavy rain","9":"Post-monsoon — lush and clear"}'::jsonb,
 ARRAY['culture','chill','food','mountains'],
 ARRAY['religious sites','cafe hopping','trekking','cooking class','local cuisine'],
 ARRAY['Dalai Lama''s temple and teachings','Incredible Tibetan food','Budget backpacker paradise','Triund trek is iconic'],
 ARRAY['Very crowded in peak season','Monsoon landslides','Steep walking everywhere','Limited luxury accommodation'],
 '[{"from":"Delhi","mode":"bus","duration_hours":10,"cost_inr":700},{"from":"Delhi","mode":"flight","duration_hours":1.5,"cost_inr":4000},{"from":"Chandigarh","mode":"drive","duration_hours":5,"cost_inr":600}]'::jsonb,
 32.2427, 76.3213,
 '{"culture,food":"Dalai Lama temple + Tibetan cooking class + Bhagsu waterfall + momo crawl","mountains,chill":"Triund trek + Bhagsu cafe hopping + monastery meditation session"}'::jsonb),

-- ══ OFFBEAT & EMERGING ══

('Ziro Valley', 'Arunachal Pradesh',
 'Rice paddy paradise — Apatani tribal culture and India''s coolest music festival',
 'budget', 8000, 20000,
 ARRAY[3,3,4,5,5,3,2,2,3,5,4,3],
 ARRAY[]::integer[],
 '{"3":"Rice planting season — beautiful green","4":"Best weather","9":"Ziro Music Festival (Sep) — unmissable"}'::jsonb,
 ARRAY['nature','culture','chill'],
 ARRAY['offbeat villages','local festivals','forests','local cuisine'],
 ARRAY['Ziro Music Festival is legendary','Unique Apatani tribe face tattoos','Stunning rice paddy landscapes','Zero commercialization'],
 ARRAY['Requires Inner Line Permit','Very remote — limited transport','Basic accommodation','Limited food options'],
 '[{"from":"Guwahati","mode":"drive","duration_hours":10,"cost_inr":1500},{"from":"Itanagar","mode":"drive","duration_hours":4,"cost_inr":600}]'::jsonb,
 27.5388, 93.8311,
 '{"nature,culture":"Apatani village walk + rice paddy trek + tribal cooking + music festival","chill,nature":"Valley walks + pine hill sunset + local rice beer + bamboo cottage stay"}'::jsonb),

('Chettinad', 'Tamil Nadu',
 'Crumbling merchant palaces with the spiciest cuisine in India — Tamil Nadu''s hidden jewel',
 'budget', 6000, 18000,
 ARRAY[4,4,3,3,2,2,2,2,3,4,5,5],
 ARRAY[]::integer[],
 '{"0":"Pongal festival — spectacular","10":"Best weather begins"}'::jsonb,
 ARRAY['culture','food'],
 ARRAY['heritage walks','crafts','cooking class','local cuisine','street food'],
 ARRAY['Mind-blowing Chettinad cuisine','Stunning abandoned mansions','Incredible tile and woodwork','Zero tourists'],
 ARRAY['Very hot most of the year','Extremely remote','No nightlife at all','Limited accommodation'],
 '[{"from":"Chennai","mode":"drive","duration_hours":7,"cost_inr":1000},{"from":"Madurai","mode":"drive","duration_hours":2,"cost_inr":300}]'::jsonb,
 10.2188, 78.8361,
 '{"culture,food":"Mansion exploration + Chettinad cooking class + Athangudi tile workshop + pepper chicken feast"}'::jsonb),

('Wayanad', 'Kerala',
 'Kerala''s green highland — tribal caves, spice gardens, and misty bamboo forests',
 'budget', 7000, 18000,
 ARRAY[4,4,3,3,3,3,3,3,3,4,5,5],
 ARRAY[]::integer[],
 '{"5":"Pre-monsoon mist — atmospheric","6":"Monsoon — lush but wet","10":"Best weather"}'::jsonb,
 ARRAY['nature','adventure','chill'],
 ARRAY['trekking','waterfalls','wildlife','forests','offbeat villages'],
 ARRAY['Edakkal Caves prehistoric art','Chembra Peak heart-shaped lake','Untouched tribal heritage','Very affordable'],
 ARRAY['Limited public transport','Leeches in monsoon','Weekend crowds from Bangalore/Kozhikode','Basic nightlife'],
 '[{"from":"Bangalore","mode":"drive","duration_hours":6,"cost_inr":800},{"from":"Kozhikode","mode":"drive","duration_hours":2,"cost_inr":400}]'::jsonb,
 11.6854, 76.1320,
 '{"nature,adventure":"Chembra Peak trek + Edakkal Caves + Meenmutty Falls rappelling","nature,chill":"Treehouse stay + spice plantation walk + bamboo rafting on Kabini"}'::jsonb),

('Orchha', 'Madhya Pradesh',
 'Forgotten Bundela capital — medieval temples and palaces with zero crowds',
 'budget', 4000, 12000,
 ARRAY[5,4,3,2,1,1,1,1,2,4,5,5],
 ARRAY[]::integer[],
 '{"3":"Pleasant but warming","10":"Best weather starts"}'::jsonb,
 ARRAY['culture','nature'],
 ARRAY['heritage walks','religious sites','wildlife'],
 ARRAY['Jahangir Mahal is stunning','Betwa river views','Virtually no tourists','Incredibly affordable'],
 ARRAY['Very hot Apr-Jun','Extremely basic infrastructure','Can be covered in 1 day','Limited food options'],
 '[{"from":"Delhi","mode":"train","duration_hours":5,"cost_inr":400},{"from":"Jhansi","mode":"drive","duration_hours":0.5,"cost_inr":100}]'::jsonb,
 25.3519, 78.6419,
 '{"culture,nature":"Jehangir Mahal + Ram Raja Temple + Betwa river raft + cenotaph sunset"}'::jsonb),

('Bir Billing', 'Himachal Pradesh',
 'Paragliding capital of India — fly over tea gardens with Dhauladhar as your backdrop',
 'budget', 5000, 15000,
 ARRAY[3,3,4,5,5,4,2,2,3,5,5,3],
 ARRAY[]::integer[],
 '{"3":"Winds picking up — pre-season","4":"Paragliding season begins","9":"Paragliding World Cup month","6":"Monsoon — no flying"}'::jsonb,
 ARRAY['adventure','nature','chill'],
 ARRAY['paragliding','trekking','cafe hopping','camping'],
 ARRAY['Best paragliding site in Asia','Tibetan colony culture','Chill backpacker vibe','Affordable mountain escape'],
 ARRAY['No flying in monsoon','Very basic town infrastructure','Limited food options','Cold winters'],
 '[{"from":"Delhi","mode":"bus","duration_hours":10,"cost_inr":700},{"from":"Chandigarh","mode":"drive","duration_hours":6,"cost_inr":600}]'::jsonb,
 32.0413, 76.7220,
 '{"adventure,chill":"Tandem paragliding + monastery visit + mountain cafe hopping","adventure,nature":"Paraglide over Kangra Valley + trek to Rajgundha meadow"}'::jsonb),

-- ══ ISLAND & UNIQUE ══

('Lakshadweep', 'Lakshadweep',
 'India''s Maldives — coral atolls with turquoise lagoons, accessible only by permit',
 'luxury', 40000, 80000,
 ARRAY[5,5,4,3,2,1,1,1,2,3,4,5],
 ARRAY[5,6,7,8],
 '{"0":"Best visibility for snorkeling","4":"Last month before monsoon closure","9":"Islands reopen"}'::jsonb,
 ARRAY['beach','nature','adventure'],
 ARRAY['water sports','secluded beaches'],
 ARRAY['Crystal clear lagoons','Pristine coral reefs','Zero commercialization','India''s cleanest beaches'],
 ARRAY['Requires special permit','Expensive — limited supply','Flights only from Kochi','Very limited accommodation','Alcohol restricted'],
 '[{"from":"Kochi","mode":"flight","duration_hours":1.5,"cost_inr":5000},{"from":"Kochi","mode":"ship","duration_hours":18,"cost_inr":3000}]'::jsonb,
 10.5667, 72.6417,
 '{"beach,nature":"Agatti lagoon + coral reef snorkeling + glass-bottom boat + island cycling","beach,adventure":"Scuba diving + kayaking + deep sea fishing + sandbank picnic"}'::jsonb),

-- ══ WEEKEND GETAWAYS ══

('Lonavala', 'Maharashtra',
 'Mumbai''s misty escape — monsoon waterfalls, cliff forts, and chikki on every corner',
 'budget', 4000, 12000,
 ARRAY[3,3,3,3,3,3,5,5,4,4,3,3],
 ARRAY[]::integer[],
 '{"6":"Monsoon magic — waterfalls everywhere, misty cliffs","7":"Peak monsoon beauty","8":"Waterfalls at full force","11":"Dry but pleasant"}'::jsonb,
 ARRAY['nature','chill','adventure'],
 ARRAY['trekking','waterfalls','sunset spots'],
 ARRAY['2 hours from Mumbai/Pune','Incredible monsoon experience','Multiple fort treks','Bhushi Dam seasonal waterfall'],
 ARRAY['Extremely crowded on weekends','Commercialized town center','Boring in non-monsoon','Traffic jams to/from Mumbai'],
 '[{"from":"Mumbai","mode":"drive","duration_hours":2,"cost_inr":300},{"from":"Pune","mode":"drive","duration_hours":1.5,"cost_inr":250}]'::jsonb,
 18.7557, 73.4091,
 '{"nature,adventure":"Rajmachi Fort trek + Bhushi Dam + Tiger''s Leap viewpoint","nature,chill":"Misty valley views + Della Adventure + chikki shopping"}'::jsonb),

('Nainital', 'Uttarakhand',
 'Lake district of India — colonial charm, boat rides, and Himalayan panoramas',
 'budget', 6000, 18000,
 ARRAY[3,3,4,5,5,4,2,2,3,4,4,3],
 ARRAY[]::integer[],
 '{"3":"Spring — pleasant, rhododendrons bloom","4":"Best weather for lake and views","6":"Monsoon — heavy rain, landslides","10":"Clear skies after monsoon"}'::jsonb,
 ARRAY['nature','chill','mountains'],
 ARRAY['hill station','valley views','cafe hopping'],
 ARRAY['Beautiful Naini Lake setting','Easy access from Delhi','Snow View Point panorama','Charming Mall Road'],
 ARRAY['Extremely crowded in summer','Traffic nightmare on weekends','Lake getting polluted','Over-commercialized'],
 '[{"from":"Delhi","mode":"drive","duration_hours":6,"cost_inr":800},{"from":"Delhi","mode":"train","duration_hours":6,"cost_inr":400}]'::jsonb,
 29.3803, 79.4636,
 '{"nature,chill":"Naini Lake boating + Mall Road stroll + Snow View cable car + cafe hopping"}'::jsonb),

-- ══ LUXURY & PREMIUM ══

('Kerala Backwaters (Kumarakom)', 'Kerala',
 'Luxury houseboat through palm canals — Michelin-worthy fish curry on floating kitchens',
 'luxury', 40000, 80000,
 ARRAY[4,4,4,3,2,2,2,2,3,4,5,5],
 ARRAY[]::integer[],
 '{"7":"Monsoon — Snake Boat Race season","8":"Nehru Trophy Boat Race","10":"Best weather begins"}'::jsonb,
 ARRAY['chill','food','nature'],
 ARRAY['local cuisine','sunset spots','spa/wellness'],
 ARRAY['Premium houseboat experience','World-class Ayurvedic resorts','Incredible Kerala cuisine','Peaceful and luxurious'],
 ARRAY['Expensive — ₹15K+ per night houseboats','Mosquitoes in evening','Limited activities beyond relaxation','Peak season gets crowded'],
 '[{"from":"Kochi","mode":"drive","duration_hours":1.5,"cost_inr":400},{"from":"Bangalore","mode":"flight","duration_hours":1,"cost_inr":3500}]'::jsonb,
 9.6175, 76.4301,
 '{"chill,food":"Premium houseboat + backwater karimeen fry + Ayurvedic spa + toddy shop visit","nature,chill":"Canoe through narrow canals + paddy field walks + sunset on Vembanad Lake"}'::jsonb),

('Jodhpur', 'Rajasthan',
 'Blue City under Mehrangarh — India''s most dramatic fort looming over indigo lanes',
 'midrange', 10000, 28000,
 ARRAY[5,5,4,3,2,1,1,1,2,4,5,5],
 ARRAY[]::integer[],
 '{"0":"Pleasant winter — best time","4":"Getting very hot","10":"Post-monsoon pleasant"}'::jsonb,
 ARRAY['culture','food','adventure'],
 ARRAY['heritage walks','street food','crafts','local cuisine','sunset spots'],
 ARRAY['Mehrangarh Fort is India''s finest','Blue city lanes are magical','Incredible street food scene','Rajasthani hospitality'],
 ARRAY['Scorching hot in summer','Old city navigation is confusing','Tourist pricing at shops','Flies and dust in old city'],
 '[{"from":"Delhi","mode":"flight","duration_hours":1.5,"cost_inr":3500},{"from":"Jaipur","mode":"train","duration_hours":5,"cost_inr":400},{"from":"Udaipur","mode":"drive","duration_hours":4,"cost_inr":600}]'::jsonb,
 26.2389, 73.0243,
 '{"culture,food":"Mehrangarh Fort + blue city walk + mirchi vada + Toorji Ka Jhalra stepwell + rooftop dinner","culture,adventure":"Zipline from fort wall + desert village safari + Bishnoi village visit"}'::jsonb),

('Auli', 'Uttarakhand',
 'India''s premier ski resort — Himalayan snow slopes with Nanda Devi panorama',
 'midrange', 12000, 30000,
 ARRAY[5,5,4,3,3,2,1,1,2,3,4,5],
 ARRAY[6,7],
 '{"0":"Peak ski season — snow guaranteed","1":"Best skiing month","3":"Last snow, spring skiing","4":"Snow melting, meadows emerging","8":"Monsoon — avoid","9":"Bugyal meadows in bloom"}'::jsonb,
 ARRAY['mountains','adventure'],
 ARRAY['snow','trekking','valley views'],
 ARRAY['Best skiing in India','Asia''s highest cable car','Nanda Devi views at sunrise','Uncrowded snow slopes'],
 ARRAY['Skiing infrastructure is basic','Remote — long drive from Rishikesh','Limited accommodation','Only worth it in winter for snow'],
 '[{"from":"Delhi","mode":"drive","duration_hours":12,"cost_inr":1500},{"from":"Rishikesh","mode":"drive","duration_hours":6,"cost_inr":800}]'::jsonb,
 30.5268, 79.5660,
 '{"mountains,adventure":"Skiing + cable car + Gorson Bugyal trek + Nanda Devi sunrise"}'::jsonb),

('Pushkar', 'Rajasthan',
 'Holy lake town with annual camel fair — where spirituality meets desert festivity',
 'budget', 4000, 12000,
 ARRAY[5,4,3,2,1,1,1,1,2,4,5,5],
 ARRAY[]::integer[],
 '{"10":"Pushkar Camel Fair (Oct/Nov) — THE reason to visit","11":"Camel Fair + pleasant weather"}'::jsonb,
 ARRAY['culture','chill','food'],
 ARRAY['religious sites','local festivals','cafe hopping','sunset spots','street food'],
 ARRAY['Pushkar Camel Fair is unique globally','Sacred Brahma Temple (only one in world)','Incredible sunset at lake ghats','Budget backpacker paradise'],
 ARRAY['Very hot most of the year','Tiny town — 1-2 days max','Aggressive touts at ghats','Alcohol and non-veg banned'],
 '[{"from":"Jaipur","mode":"drive","duration_hours":3,"cost_inr":400},{"from":"Delhi","mode":"train","duration_hours":8,"cost_inr":500}]'::jsonb,
 26.4897, 74.5511,
 '{"culture,chill":"Brahma Temple + lake ghat sunset + rooftop cafe + camel fair (if Nov)","culture,food":"Temple walk + street food in bazaar + cooking class + desert sunset"}'::jsonb),

('Kodaikanal', 'Tamil Nadu',
 'Princess of Hill Stations — misty pine forests, star-shaped lake, and homemade chocolate',
 'budget', 6000, 18000,
 ARRAY[4,4,4,4,4,3,3,3,3,4,5,5],
 ARRAY[]::integer[],
 '{"4":"Summer crowds peak","6":"Monsoon mist — romantic but wet","10":"Best weather begins"}'::jsonb,
 ARRAY['nature','chill','mountains'],
 ARRAY['hill station','waterfalls','sunset spots','cafe hopping'],
 ARRAY['Star-shaped lake is unique','Beautiful pine forest walks','Homemade chocolate and cheese','Less crowded than Ooty'],
 ARRAY['Limited adventure activities','Foggy roads in monsoon','Basic town infrastructure','Crowds in summer holidays'],
 '[{"from":"Chennai","mode":"drive","duration_hours":9,"cost_inr":1200},{"from":"Madurai","mode":"drive","duration_hours":3,"cost_inr":400},{"from":"Bangalore","mode":"drive","duration_hours":8,"cost_inr":1000}]'::jsonb,
 10.2381, 77.4892,
 '{"nature,chill":"Lake cycling + Coaker''s Walk + pine forest picnic + homemade chocolate shopping"}'::jsonb),

-- ══ MORE DESTINATIONS ══

('Agra', 'Uttar Pradesh',
 'Taj Mahal at sunrise — the monument of love needs no introduction',
 'budget', 5000, 15000,
 ARRAY[5,4,3,2,1,1,1,1,2,4,5,5],
 ARRAY[]::integer[],
 '{"0":"Best weather for Taj sunrise","3":"Last comfortable month","10":"Festival season, pleasant weather"}'::jsonb,
 ARRAY['culture'],
 ARRAY['heritage walks','religious sites'],
 ARRAY['Taj Mahal — enough said','Agra Fort is underrated','Close to Delhi (3hrs)','Petha sweets are famous'],
 ARRAY['Can be covered in 1 day','Extreme heat in summer','Aggressive touts everywhere','Pollution affecting marble'],
 '[{"from":"Delhi","mode":"train","duration_hours":2,"cost_inr":300},{"from":"Delhi","mode":"drive","duration_hours":3,"cost_inr":500},{"from":"Jaipur","mode":"drive","duration_hours":4,"cost_inr":600}]'::jsonb,
 27.1767, 78.0081,
 '{"culture":"Taj at sunrise + Agra Fort + Mehtab Bagh sunset view + Petha tasting"}'::jsonb),

('Amritsar', 'Punjab',
 'Golden Temple glory and Wagah border drama — India''s most soulful city',
 'budget', 5000, 15000,
 ARRAY[4,4,4,3,2,1,1,1,2,4,5,5],
 ARRAY[]::integer[],
 '{"0":"Lohri + pleasant weather","3":"Baisakhi (Apr) — Sikh New Year celebrations","10":"Diwali at Golden Temple — spectacular"}'::jsonb,
 ARRAY['culture','food'],
 ARRAY['religious sites','street food','local cuisine','heritage walks'],
 ARRAY['Golden Temple is transcendent','Best street food in India','Wagah Border ceremony is electric','Langar (free community kitchen) experience'],
 ARRAY['Very hot in summer','Can be covered in 2 days','Traffic in old city','Limited beyond GT and temple'],
 '[{"from":"Delhi","mode":"train","duration_hours":6,"cost_inr":500},{"from":"Delhi","mode":"flight","duration_hours":1,"cost_inr":3000}]'::jsonb,
 31.6340, 74.8723,
 '{"culture,food":"Golden Temple + Jallianwala Bagh + Wagah Border + Amritsari kulcha crawl + lassi","culture":"Golden Temple night + Partition Museum + heritage walk through old city"}'::jsonb),

('Kasol', 'Himachal Pradesh',
 'Mini Israel of India — Parvati Valley trekker paradise with riverside camping',
 'budget', 4000, 12000,
 ARRAY[2,2,3,4,5,4,2,2,3,5,4,2],
 ARRAY[]::integer[],
 '{"4":"Perfect trekking weather begins","5":"Best month — warm, clear, green","6":"Monsoon — river floods, avoid","9":"Post-monsoon — trails clear"}'::jsonb,
 ARRAY['adventure','nature','chill'],
 ARRAY['trekking','camping','cafe hopping','offbeat villages'],
 ARRAY['Kheerganga hot springs trek','Israeli-influenced cafe culture','Stunning Parvati Valley','Very budget-friendly'],
 ARRAY['Overcrowded in summer','Drug culture reputation','Garbage issues on trails','Flash floods in monsoon','Limited medical facilities'],
 '[{"from":"Delhi","mode":"bus","duration_hours":12,"cost_inr":700},{"from":"Chandigarh","mode":"drive","duration_hours":7,"cost_inr":800}]'::jsonb,
 32.0101, 77.3149,
 '{"adventure,nature":"Kheerganga trek + Malana village + Tosh valley + riverside camping","chill,nature":"Riverside cafe hopping + Chalal walk + hot springs + stargazing"}'::jsonb),

('Gangtok', 'Sikkim',
 'Clean mountain capital with Kanchenjunga views — Buddhist peace meets Himalayan adventure',
 'midrange', 12000, 28000,
 ARRAY[3,3,4,5,5,3,1,1,2,5,4,3],
 ARRAY[6,7],
 '{"3":"Spring — rhododendrons bloom everywhere","4":"Best month — clear Kanchenjunga views","5":"Still good but clouds building","9":"Post-monsoon — dramatic skies"}'::jsonb,
 ARRAY['mountains','nature','adventure','culture'],
 ARRAY['trekking','valley views','religious sites','wildlife','offbeat villages'],
 ARRAY['Kanchenjunga sunrise at Tiger Hill','Tsomgo Lake is magical','Clean, well-organized city','Nathula Pass China border'],
 ARRAY['Permits required for many areas','Monsoon landslides','Limited flight connectivity','Altitude sickness at higher points'],
 '[{"from":"Kolkata","mode":"flight","duration_hours":1.5,"cost_inr":4500},{"from":"Delhi","mode":"flight","duration_hours":2.5,"cost_inr":6000},{"from":"Siliguri","mode":"drive","duration_hours":4,"cost_inr":600}]'::jsonb,
 27.3389, 88.6065,
 '{"mountains,adventure":"Tsomgo Lake + Nathula Pass + Goechala trek + river rafting Teesta","mountains,culture":"Rumtek Monastery + Enchey Monastery + MG Marg walk + momos crawl"}'::jsonb),

('Pondicherry Beach Towns', 'Tamil Nadu',
 'Mahabalipuram to Tranquebar — ancient temples on pristine shores nobody visits',
 'budget', 5000, 15000,
 ARRAY[5,5,4,3,2,2,2,2,3,4,5,5],
 ARRAY[]::integer[],
 '{"0":"Perfect beach weather","11":"Northeast monsoon starts — can be rough"}'::jsonb,
 ARRAY['culture','beach','chill'],
 ARRAY['heritage walks','secluded beaches','local cuisine'],
 ARRAY['Mahabalipuram UNESCO shore temples','Danish fort at Tranquebar','Zero tourists on most beaches','Rich Chola history'],
 ARRAY['Hot and humid most of year','Limited accommodation in smaller towns','Basic infrastructure','Cyclone risk Nov-Dec'],
 '[{"from":"Chennai","mode":"drive","duration_hours":1.5,"cost_inr":300},{"from":"Pondicherry","mode":"drive","duration_hours":2,"cost_inr":400}]'::jsonb,
 12.6269, 80.1927,
 '{"culture,beach":"Shore Temple sunrise + Arjuna''s Penance + coastal drive to Tranquebar Danish fort"}'::jsonb),

('Valley of Flowers', 'Uttarakhand',
 'UNESCO alpine meadow — 600+ flower species blooming at 12,000ft, accessible only by trek',
 'midrange', 12000, 25000,
 ARRAY[1,1,1,1,2,3,5,5,4,2,1,1],
 ARRAY[0,1,2,3,9,10,11],
 '{"6":"Monsoon begins — early flowers","7":"Peak bloom — 300+ species visible","8":"Full glory — brahma kamal blooms","9":"Season ending"}'::jsonb,
 ARRAY['nature','adventure'],
 ARRAY['trekking','waterfalls','wildlife','forests'],
 ARRAY['UNESCO World Heritage Site','600+ flower species','Hemkund Sahib pilgrimage nearby','Truly unique experience'],
 ARRAY['Only accessible Jul-Sep','13km trek each way','Altitude sickness risk','Very basic camp accommodation','Permit required'],
 '[{"from":"Delhi","mode":"drive","duration_hours":10,"cost_inr":1200},{"from":"Rishikesh","mode":"drive","duration_hours":6,"cost_inr":800}]'::jsonb,
 30.7280, 79.6053,
 '{"nature,adventure":"Trek through alpine meadows + 600 flower species + Hemkund Sahib lake at 15,000ft"}'::jsonb);
